---
# File: tasks/main.yml - Ansible Hubot main tasks

- name: Make sure hubot_admin user exists
  user: name={{ hubot_admin }} state=present

# CentOS tasks
- include: CentOS.yml
  when: ansible_distribution  == "CentOS"

# Ubuntu tasks
- include: Ubuntu.yml
  when: ansible_distribution  == "Ubuntu"
